In [1]:
#Numpy

import numpy as np

#Creating a 1-D Ndarray

a=np.array([12, 23, 45, 56, 78])
print(a)
print(type(a))

[12 23 45 56 78]
<class 'numpy.ndarray'>


In [2]:
#Creating a 2-d Ndarray of size row=3, col=2

a1=np.array([[10, 12], [20, 22], [30, 32]])
print(a1)
print(type(a1))

[[10 12]
 [20 22]
 [30 32]]
<class 'numpy.ndarray'>


In [3]:
#To view  the shape of the ndarray
print('Shape of Ndarray a1:', a1.shape)

print('Number of Rows in a1:', a1.shape[0])
print('Number of Cols in a1:', a1.shape[1])

Shape of Ndarray a1: (3, 2)
Number of Rows in a1: 3
Number of Cols in a1: 2


In [4]:
#To know the size of the array
print('Size of the Ndarray a1:', a1.size)

Size of the Ndarray a1: 6


In [5]:
#to view the datatype of Ndarray element
print('Data type of each element of Ndarray a1:', a1.dtype)

Data type of each element of Ndarray a1: int32


In [6]:
#To view the size of each element of Ndarray
print('Size of each element of Ndarray a1:', a1.itemsize, 'Bytes')

Size of each element of Ndarray a1: 4 Bytes


In [7]:
#reshaping a Ndarray

#reshape(row, col)
print('Original Array:\n', a1)

#reshaping a1 to (2, 3)
a1=a1.reshape(2,3)
print('')
print('Array after reshaping:\n', a1)

Original Array:
 [[10 12]
 [20 22]
 [30 32]]

Array after reshaping:
 [[10 12 20]
 [22 30 32]]


In [9]:
a2=np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10])
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Array slicing 
print('Elements from index=2 to index=6:', a2[2:7])
print('Elements from index=3 to index=8:', a2[3:9])


Elements from index=2 to index=6: [3 4 5 6 7]
Elements from index=3 to index=8: [4 5 6 7 8 9]
Elements from index=6 to index=end: [ 7  8  9 10]
Elements from index=0 to index=7: [1 2 3 4 5 6 7 8]


In [24]:
print('Elements from index=6 to index=end:', a2[6:])
print('Elements from index=6 to index=end:', a2[6:-1])
print('Last element:', a2[-1])

Elements from index=6 to index=end: [ 7  8  9 10]
Elements from index=6 to index=end: [7 8 9]
Last element: 10


In [16]:
print('Elements from index=0 to index=7:', a2[:8])
print('Elements from index=0 to index=7:', a2[0:8])


Elements from index=0 to index=7: [1 2 3 4 5 6 7 8]
Elements from index=0 to index=7: [1 2 3 4 5 6 7 8]


In [2]:
#numpy functions

a1=np.array([10,12, 14, 16, 18, 20])
print('array:\n', a1)

array:
 [10 12 14 16 18 20]


In [3]:
#min():

print('Minimum element of the array:', a1.min())

Minimum element of the array: 10


In [4]:
#max():
print('Maximum element in array a1:', a1.max())

Maximum element in array a1: 20


In [5]:
#sum():
    print('Sum of element of array a1:', a1.sum())

Sum of element of array a1: 90


In [6]:
#2D Array

a2=np.array([[12, 4, 10], [14, 8, 20], [10, 5, 16]])
a2

array([[12,  4, 10],
       [14,  8, 20],
       [10,  5, 16]])

In [7]:
#To obtain maximum element column wise
print('Maximum element in each column:', a2.max(axis=0))

Maximum element in each column: [14  8 20]


In [10]:
#To obtain maximum element column wise
max_col=a2.max(axis=0)
print('Maximum element in each column:',max_col)
print('Maximum element in first column:', max_col[0])
print('Maximum element in second column:', max_col[1])

Maximum element in each column: [14  8 20]
Maximum element in first column: 14
Maximum element in second column: 8


In [12]:
#To obtain maximum element row wise
print('Maximum element in each row:', a2.max(axis=1))

Maximum element in each row: [12 20 16]


In [14]:
#To obtain minimum element column wise
print('Minimum element in each column:', a2.min(axis=0))

Minimum element in each column: [10  4 10]


In [15]:
#To obtain minimum element row wise
print('Minimum element in each row:', a2.min(axis=1))

Minimum element in each row: [4 8 5]


In [16]:
#To obtain sum column wise
print('sum of each column:', a2.sum(axis=0))

sum of each column: [36 17 46]


In [17]:
#To obtain sum row wise
print('sum of each row:', a2.sum(axis=1))

sum of each row: [26 42 31]


In [18]:
print('Array a1:', a1)

Array a1: [10 12 14 16 18 20]


In [19]:
#sqrt(): used to obtain the square root of each element of numpy ndarray

print('Square root of array a1:\n', np.sqrt(a1))

Square root of array a1:
 [3.16227766 3.46410162 3.74165739 4.         4.24264069 4.47213595]


In [20]:
print('Square root of array a2:\n', np.sqrt(a2))

Square root of array a2:
 [[3.46410162 2.         3.16227766]
 [3.74165739 2.82842712 4.47213595]
 [3.16227766 2.23606798 4.        ]]


In [21]:
#mean(): to obtain mean/average of the numpy ndarray
print('Mean of array a1:', np.mean(a1))

Mean of array a1: 15.0


In [22]:
print('Mean of array a2:', np.mean(a2))

Mean of array a2: 11.0


In [23]:
#std(): to obtain standard daviation of the numpy ndarray

print('standard daviation of array a1:', np.std(a1))


standard daviation of array a1: 3.415650255319866


In [24]:
print('standard daviation of array a2:', np.std(a2))


standard daviation of array a2: 4.853406592853679


In [25]:
#Arithmetic operation on Ndarray

a=np.array([[1,2,3], [4,5,6], [7,8,9]])
b=np.array([[2,4,6], [8,10,12], [14,16,18]])

print('Array A:\n', a)
print('Array B:\n', b)

Array A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array B:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [26]:
print('Sum of array a and b:\n', a+b)


Sum of array a and b:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [27]:
print('Difference of array a and b:\n', a-b)


Difference of array a and b:
 [[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]


In [28]:
print('Multiplication of array a and b:\n', a*b)


Multiplication of array a and b:
 [[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


In [29]:
print('Division of array a and b:\n', a/b)


Division of array a and b:
 [[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [30]:
x=np.array([[1,2], [3,4]])
y=np.array([[5,6], [7,8]])
print('X array:\n', x)
print('Y array:\n', y)

X array:
 [[1 2]
 [3 4]]
Y array:
 [[5 6]
 [7 8]]


In [31]:
#Array concatenation
#hstack():to concatenate array horizontally

print('Array Horizontal concatenation:\n', np.hstack((x,y)))

Array Horizontal concatenation:
 [[1 2 5 6]
 [3 4 7 8]]


In [32]:
#vstack(): to concatenate array vertically

print('Array Vertical concatenation:\n', np.vstack((x,y)))

Array Vertical concatenation:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
#empty()
ar_empty=np.empty((3,2), dtype=np.float)
print('Creating an empty array of 3*2:\n', ar_empty)

Creating an empty array of 3*2:
 [[25.  9.]
 [ 1.  1.]
 [ 9. 25.]]


C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [35]:
#zeros():
ar_zero=np.zeros((2,3), dtype=np.int)
ar_zero

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
#ones()

ar_ones=np.ones((4,3), dtype=int)
ar_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [37]:
#asarray():
li=[1,2,3,4,5,6]

arr=np.asarray(li)
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [39]:
#arange()

aran=np.arange(1, 10, dtype=int)
aran

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
aran=np.arange(1, 10, 2, dtype=int)
aran

array([1, 3, 5, 7, 9])

In [41]:
aran=np.arange(18, 2, -2, dtype=int)
aran

array([18, 16, 14, 12, 10,  8,  6,  4])

In [42]:
#Array broadcasting
x1=np.array([[1,2,3], [4,5,6]])
y1=np.array([[2,4,6]])

In [43]:
x1+y1

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [44]:
x1-y1

array([[-1, -2, -3],
       [ 2,  1,  0]])

In [45]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
print("Printing array:")
print(a);
print("Iterating over the array:")

for x in np.nditer(a):
    print(x,end=' ')


Printing array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3 

In [50]:
r=89.456677
print('Rounding the value of "r" upto 2 decimal places:', np.around(r, 2))
print('Rounding the value of "r" upto 3 decimal places:', np.around(r, 3))
print('Rounding the value of "r" upto 1 decimal places:', np.around(r, 1))
print('Rounding the value of "r" upto 0 decimal places:', np.around(r, 0))
print('Rounding the value of "r" upto -1 decimal places:', np.around(r, -1))

Rounding the value of "r" upto 2 decimal places: 89.46
Rounding the value of "r" upto 3 decimal places: 89.457
Rounding the value of "r" upto 1 decimal places: 89.5
Rounding the value of "r" upto 0 decimal places: 89.0
Rounding the value of "r" upto -1 decimal places: 90.0


In [53]:
ro=np.array([12.34455, 23.45567, 33.455566, 12.34445555, 88.44559988])
print('Original array:', ro)
print('Rounding the value of "ro" upto 2 decimal places:', np.around(ro, 2))

Original array: [12.34455    23.45567    33.455566   12.34445555 88.44559988]
Rounding the value of "ro" upto 2 decimal places: [12.34 23.46 33.46 12.34 88.45]


In [54]:
#linspace():

#Creating a array of 5 element between 1 to 10
#Syntax: linspace(start, end, no_of_element)

ar1=np.linspace(1, 10, 5)
ar1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [55]:
#Creating a array of 6 element between 3 to 18
ar2=np.linspace(3,18, 6)
ar2

array([ 3.,  6.,  9., 12., 15., 18.])

In [ ]:
#floor value

Ex r=12.34

Floor value=12


r1=34.89

floor value=34

#ceiling value

ceiling value of r=13

ceiling value of r1= 35


In [57]:
#floor()

q1=56.67
print('Floor value of q1:', np.floor(q1))

q2=56.34
print('Floor value of q2:', np.floor(q2))

Floor value of q1: 56.0
Floor value of q2: 56.0


In [60]:
#ceil()
print('ceiling value of q1:', np.ceil(q1))
print('ceiling value of q2:', np.ceil(q2))


ceiling value of q1: 57.0
ceiling value of q2: 57.0


In [61]:
ro

array([12.34455   , 23.45567   , 33.455566  , 12.34445555, 88.44559988])

In [62]:
print('Floor value of ro:', np.floor(ro))

print('ceiling value of ro:', np.ceil(ro))


Floor value of ro: [12. 23. 33. 12. 88.]
ceiling value of ro: [13. 24. 34. 13. 89.]


In [63]:
a = np.array([[2,10,20],[80,43,31],[22,90,18]])  
print("The original array:\n")  
print(a)  

print("\nThe minimum element among the columns of  array",np.amin(a,0))  

print("The maximum element among the columns of array",np.amax(a,0))  
  



The original array:

[[ 2 10 20]
 [80 43 31]
 [22 90 18]]

The minimum element among the columns of  array [ 2 10 18]
The maximum element among the columns of array [80 90 31]


In [64]:
print("\nThe minimum element among the rows of array",np.amin(a,1))  
print("The maximum element among the rows of array",np.amax(a,1)) 



The minimum element among the rows of array [ 2 31 18]
The maximum element among the rows of array [20 80 90]


In [66]:
a

array([[ 2, 10, 20],
       [80, 43, 31],
       [22, 90, 18]])

In [65]:
#ptp()

print('Column wise range in Array a:', np.ptp(a, 0))

Column wise range in Array a: [78 80 13]


In [67]:
print('Row wise range in Array a:', np.ptp(a, 1))

Row wise range in Array a: [18 49 72]


In [68]:
a

array([[ 2, 10, 20],
       [80, 43, 31],
       [22, 90, 18]])

In [69]:
print('Sorting Row wise:')
print(np.sort(a))

Sorting Row wise:
[[ 2 10 20]
 [31 43 80]
 [18 22 90]]


In [70]:
print('Sorting Column wise:')
print(np.sort(a,0))

Sorting Column wise:
[[ 2 10 18]
 [22 43 20]
 [80 90 31]]
